version: '3'

networks:
  all:
    external: True

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    networks:
        - all
    volumes:
        - ./data:/opt/zookeeper-3.4.6/data
    ports:
        - "2181:2181"
        - "2182:2182"
    restart: always

  kafka-ui:
    image: freakchicken/kafka-ui-lite
    networks:
        - all
    ports:
        - 8889:8889
    restart: always
