version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    restart: always