version: '3'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ':9001' /data
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
        MINIO_ACCESS_KEY: root
        MINIO_SECRET_KEY: rootroot
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    privileged: true
    restart: always
