version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    volumes:
        - ./data:/data
        - ./redis.conf:/etc/redis/redis.conf
    ports:
        - "6379:6379"
    restart: always
